# configs/config.yaml

# Google Cloud Storage
gcs:
  bucket: bucket-clash-royal-ai
  prefix: frames/

# Label Studio
labelstudio:
  url: http://localhost:8080
  api_key: e73c69c8b83fdf2b539cd4e468ef84f49ea78ddd
  project_id: 9

# Frame Extraction
extraction:
  fps: 2
  quality: 95

# Dataset Splitting
dataset:
  train_ratio: 0.8
  val_ratio: 0.2
  random_seed: 42

# Training
training:
  epochs: 30
  batch_size: 4
  img_size: 640
  device: mps  # Use 'mps' for M1/M2 Macs, 'cpu' as fallback

# Classes
classes:
  - deployment